apiVersion: v1
kind: Pod
metadata:
  name: configmap-example-pod-config
spec:
  containers:
    - name: configmap-example-busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: APPLICATION_TYPE
          valueFrom:
            configMapKeyRef:
               name: application-configs
               key: app.type
        - name: APPLICATION_UI_TYPE
          valueFrom:
            configMapKeyRef:
               name: application-configs
               key: app.ui
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
               name: application-log-configs
               key: log_level
  restartPolicy: Never
