apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
spec: 
  containers: 
    - image: redis
      name: redis-pod
      volumeMounts: 
        - mountPath: /etc/dbcreds
          name: dbcreds
          readOnly: true
  volumes: 
    - name: dbcreds
      secret: 
        secretName: mysecret

